candidatos/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('info/', include('info.urls')),
    path('admin/', admin.site.urls),
]

info/urls.py
from django.urls import path

from . import views

app_name = 'info'

urlpatterns = [
    path('', views.index, name='index'),
     # ex: /listado/
    path('listado', views.listado, name='listado'),
    # ex: /detalle/5/
    path('detalle/<int:candidato_id>/', views.detalle, name='detalle'),
]

info/models.py
from django.db import models
from datetime import date

# Create your models here.
class Candidato(models.Model):
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    fecha_nac = models.DateField('Fecha de nacimiento',default=date.today)
    fecha_in_polt = models.DateField('Fecha de inicio en la política', default=date.today)

    #Es importante añadir los métodos __str__() a sus modelos, para representaciones de objetos se usan en todo el sitio administrativo generado automáticamente de Django.
    def __str__(self):
        return self.nombres + " " + self.apellidos

info/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.http import Http404
from .models import Candidato

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def listado(request):
    candidatos = Candidato.objects.all()
    context = { 'candidatos': candidatos }
    return render(request, 'info/index.html', context)

def detalle(request, candidato_id):
    try:
        candidato = Candidato.objects.get(id=candidato_id)
    except Candidato.DoesNotExist:
        raise Http404("Ese candidato no existe")
    return render(request, 'info/detalle.html', {'candidato': candidato})

info/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>CandidatosApp</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <h1> Saldrá en todo lado</h1>
        {% block body %}
        {% endblock %}
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    </body>
</html>

info/templates/info/detalle.html
{{ candidato }}

info/templates/info/index.html
{% extends 'base.html' %}
    {% block body %}
        {% if candidatos %}
            <ul>
            {% for candidato in candidatos %}
                <li><a href="{% url 'info:detalle' candidato.id %}">{{ candidato.nombres }} {{ candidato.apellidos }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>Lista de candidatos.</p>
        {% endif %}
    {% endblock%}